version: "3.8"

services:
  # Наше мобильное приложение (Web-версия)
  app:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - /app/node_modules # Важно: не даем локальному node_modules перезаписать контейнерный
    command: npx expo start --web --port 8081
    environment:
      - NODE_ENV=development

  # Наш имитатор бэкенда
  server:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    # Запускаем json-server на все интерфейсы (0.0.0.0)
    command: npx json-server --watch db.json --host 0.0.0.0 --port 3000
